title: Dylan Kakkanad's Portfolio
description: Portfolio and Blog of a Software Developer
baseurl: ""
url: "https://dylan-kakkanad.github.io"
github_username: dylan-kakkanad

# Build settings
include:
  - _pages
  - _pages/categories

# Permalink structure for blog posts
permalink: /blog/:year/:month/:day/:title/

# Markdown and syntax highlighting settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Syntax highlighter theme
highlighter: rouge

# Plugins (if you're using GitHub Pages)
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
